apiVersion: v1
kind: Pod
metadata:
  name: spring-boot-demo
  labels:
    app: gce-app
spec:
  containers:
  - name: gce-demo
    image: gcr.io/spring-boot-demo-168110:1.0
    ports:
    - name: springb-port
      containerPort: 8080
