apiVersion: v1
kind: Service
metadata:
  name: cms-frontend-service
spec:
  ports:
  - port: 80
    targetPort: frontend-port
    protocol: TCP
  selector:
    app:  appdirect-cms-frontend
  type: LoadBalancer
