apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: appdirect-cms-backend-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: appdirect-cms-backend
    spec:
      containers:
      - name: appdirect-cms-backend
        image: gcr.io/spring-boot-demo-168110/appdirect-cms-backend:1.0
        ports:
        - name: backend-port
          containerPort: 3001
        env:
        - name: DATABASE_USER
          value:  root
        - name: DATABASE_PASS
          value:  pass123
        - name: DATABASE_HOST
          value:  mysql-service
