apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: appdirect-cms-migration-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: appdirect-cms-migration
    spec:
      containers:
      - name: appdirect-cms-migration
        image: gcr.io/spring-boot-demo-168110/appdirect-cms-backend:1.0
        args: ["bundle", "exec", "rake", "db:create", "db:migrate"]
        ports:
        - name: migration-port
          containerPort: 3001
        env:
        - name: DATABASE_USER
          value:  root
        - name: DATABASE_PASS
          value:  pass123
        - name: DATABASE_HOST
          value:  mysql-service
        - name: RAILS_ENV
          value:  production


